language: python
python: 
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
script: pytest app.py
notifications:
  email:
    recipients:
      - vpokhapkin@yandex.ru
    on_success: never
    on_failure: change